export const MAIN_TEST_LOAD = "MAIN_TEST_LOAD";
export const MAIN_TEST_SUCCESS = "MAIN_TEST_SUCCESS";
export const MAIN_TEST_FAIL = "MAIN_TEST_FAIL";

export const SECOND_TEST_LOAD = "SECOND_TEST_LOAD";
export const SECOND_TEST_SUCCESS = "SECOND_TEST_SUCCESS";
export const SECOND_TEST_FAIL = "SECOND_TEST_FAIL";

export const INCREMENT_CURRENT_QUESTION = "INCREMENT_CURRENT_QUESTION";
export const INCREMENT_CURRENT_CATEGORY = "INCREMENT_CURRENT_CATEGORY";
export const INCREMENT_CURRENT_TEST_FAIL = "INCREMENT_CURRENT_TEST_FAIL";

export const SKIP_CATEGORY = "SKIP_CATEGORY";
export const SKIP_CATEGORY_FAIL = "SKIP_CATEGORY_FAIL";

export const SIGN_IN_LOAD = "SIGN_IN_LOAD";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const SIGN_UP_LOAD = "SIGN_UP_LOAD";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const SIGN_OUT = "SIGN_OUT";

export const GET_SIGN_IN_INFO = "GET_SIGN_IN_INFO";
export const PRELOAD_DONE = "PRELOAD_DONE";

export const SHOW_SNACK_BAR = "SHOW_SNACK_BAR";
export const HIDE_SNACK_BAR = "HIDE_SNACK_BAR";

export const GOALS_LOAD = "GOALS_LOAD";
export const GOALS_SUCCESS = "GOALS_SUCCESS";
export const GOALS_FAIL = "GOALS_FAIL";

export const USER_GOALS_LOAD = "USER_GOALS_LOAD";
export const USER_GOALS_SUCCESS = "USER_GOALS_SUCCESS";
export const USER_GOALS_FAIL = "USER_GOALS_FAIL";

export const UPDATE_TASK_LOAD = "UPDATE_TASK_LOAD";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const TASK_LOAD = "TASK_LOAD";
export const TASK_SUCCESS = "TASK_SUCCESS";
export const TASK_FAIL = "TASK_FAIL";

export const FAIL_USER_GOAL_LOAD = "FAIL_USER_GOAL_LOAD";
export const FAIL_USER_GOAL_SUCCESS = "FAIL_USER_GOAL_SUCCESS";
export const FAIL_USER_GOAL_FAIL = "FAIL_USER_GOAL_FAIL";

export const UPDATE_USER_GOAL_LOAD = "UPDATE_USER_GOAL_LOAD";
export const UPDATE_USER_GOAL_SUCCESS = "UPDATE_USER_GOAL_SUCCESS";
export const UPDATE_USER_GOAL_FAIL = "UPDATE_USER_GOAL_FAIL";

export const START_USER_GOAL_LOAD = "START_USER_GOAL_LOAD";
export const START_USER_GOAL_SUCCESS = "START_USER_GOAL_SUCCESS";
export const START_USER_GOAL_FAIL = "START_USER_GOAL_FAIL";

export const CREATE_FIRST_TASK_LOAD = "CREATE_FIRST_TASK_LOAD";
export const CREATE_FIRST_TASK_SUCCESS = "CREATE_FIRST_TASK_SUCCESS";
export const CREATE_FIRST_TASK_FAIL = "CREATE_FIRST_TASK_FAIL";

export const SET_CURRENT_GOAL = "SET_CURRENT_GOAL";
export const SET_CURRENT_GOAL_FAIL = "SET_CURRENT_GOAL_FAIL";
