export const MAIN_TEST_LOAD = "MAIN_TEST_LOAD";
export const MAIN_TEST_SUCCESS = "MAIN_TEST_SUCCESS";
export const MAIN_TEST_FAIL = "MAIN_TEST_FAIL";

export const INCREMENT_CURRENT_QUESTION = "INCREMENT_CURRENT_QUESTION";
export const INCREMENT_CURRENT_CATEGORY = "INCREMENT_CURRENT_CATEGORY";
export const INCREMENT_CURRENT_TEST_FAIL = "INCREMENT_CURRENT_TEST_FAIL";

export const SIGN_IN_LOAD = "SIGN_IN_LOAD";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const SIGN_UP_LOAD = "SIGN_UP_LOAD";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const SIGN_OUT = "SIGN_OUT";

export const GET_SIGN_IN_INFO = "GET_SIGN_IN_INFO";
export const PRELOAD_DONE = "PRELOAD_DONE";

export const SHOW_SNACK_BAR = "SHOW_SNACK_BAR";
export const HIDE_SNACK_BAR = "HIDE_SNACK_BAR";
